# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a90f2d9ca051ee490c49fa1f660b5ae0d38b8d369c728c5e5b6fb2d7ed41b2c07f9c9af1f81766813045d5a907725e7616a3d193dba651c7062b8599c1dab3e

test:
  secret_key_base: d4f69ad5d9e98f0db3dbb7d2ae3fea09c9a2bc3423602e01cd2c74ceb30a7b7dd5a51f808a41aa58cf469a307a83c383da7b902e78dd1e95ba35f7f208b1b4f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
